- src/MonitoringTargetStage.ts
> fix: add notificationchannel again

- src/main.ts
> feat: add deployment for auth-prod

- src/DeploymentEnvironment.ts
- src/DeploymentEnvironments.ts
- src/MonitoringTargetStage.ts
- src/PipelineStack.ts
- src/main.ts
- also moved environments to their own file
fixes #31
> feat: added Production and Development accounts

- src/DeploymentEnvironments.ts
Verkeerde account-id opgezocht.
> fix: Fixed account id for production

- src/DefaultAlarms.ts
- src/LogLambda/MessageFormatter.ts
- src/LogLambda/index.ts
- src/LogLambda/test/events-to-slack.test.ts
- src/LogLambda/test/samples/messages/certificate-approaching-expiry.json
- src/LogLambda/test/samples/messages/event-devopsguru-insight.json
- src/LogLambda/test/samples/messages/event-devopsguru-severity-upgraded.json
- src/MonitoringTargetStage.ts
- feat: Add DevopsGuru support to lambda 
- feat: Listen for eventbridge events from devopsguru. (fixes #30 )
- feat: Add handler for certificate expiry events
> feat: expand monitoring

- src/LogLambda/MessageFormatter.ts
- src/LogLambda/index.ts
- src/MonitoringTargetStage.ts
added codepipeline events to the possible subscriptions
> feat: codepipeline events in slack

- src/LogLambda/MessageFormatter.ts
- src/LogLambda/index.ts
- src/LogLambda/test/events-to-slack.test.ts
- Monitoring rule for codepipeline
- Message formatter for codepipeline
- Deploy to deployment aws account
- include and exclude event subscriptions per account by id
> feat: codepipeline monitoring

- README.md
- src/LogLambda/index.ts
- src/MonitoringLambda.ts
- src/MonitoringTargetStage.ts
- src/statics.ts
Adds second slack webhook, configures pipeline changes to use that webhook.
> feat: Allow low priority notifications to slack

- src/LogLambda/MessageFormatter.ts
- src/LogLambda/index.ts
- src/MonitoringTargetStage.ts
Fixes https://github.com/GemeenteNijmegen/devops/issues/126
> feat: add health dashboard alerts to monitoring channel

- src/LogLambda/MessageFormatter.ts
- src/LogLambda/index.ts
- src/MonitoringTargetStage.ts
Fixes https://github.com/GemeenteNijmegen/devops/issues/8
> feat: inspector finding notifications

- src/DeploymentEnvironments.ts
- src/MonitoringTargetStage.ts
> feat: Don't enable devopsguru by default

- src/LogLambda/MessageFormatter.ts
- src/MonitoringTargetStage.ts
ec2 pending / started events to slack
> feat: ec2 pending and start events

- src/DefaultAlarms.ts
Fixes https://github.com/GemeenteNijmegen/devops/issues/169
> feat: access denied notification

- .projen/tasks.json
- .projenrc.js
- src/DefaultAlarms.ts
- src/LogSubscriptionLambda.ts
- src/LogSubscriptionsLambda/MessageFormatter.ts
- src/LogSubscriptionsLambda/index.ts
- src/LogSubscriptionsLambda/package-lock.json
- src/LogSubscriptionsLambda/package.json
- src/LogSubscriptionsLambda/template.json
- src/LogSubscriptionsLambda/test/index.test.ts
- src/MonitoringTargetStage.ts
- Nieuwe lambda voor log subscriptions in elk account
- Ipv alarm op CloudTrail log nu een log subscription
> feat: LogSubscriptionLambda

- src/LogSubscriptionLambda.ts
> fix: missing invokation permission

- src/LogLambda/LogsEventHandler.ts
- src/LogLambda/test/samples/log-event.json
Exclude error for SNS dummy topic
> feat: Exclude securityhub role error

- src/MonitoringTargetStage.ts
- src/SlackIntegrationStack.ts
> fix: undeploy slack-integrations stack (rename)

- docs/Streams.md
- src/monitoringLambda/SlackMessage.ts
> fix: channel/app/topic overview

- src/monitoringLambda/SlackMessage.ts
> fix: log block and check if json is escaped

- src/monitoringLambda/SlackMessage.ts
> fix: make sure the blocks are properly stringified before posting

- src/monitoringLambda/MessageFormatter.ts
> feat: slack interactivity integration alarm messages

- src/SlackInteractivityLambda/SlackInteractivity.lambda.ts
- src/monitoringLambda/SlackMessage.ts
> fix: use base64 string to send value payload

- src/SlackInteractivityLambda/SlackInteractivity.lambda.ts
- src/monitoringLambda/SlackMessage.ts
- test/SlackMessage.test.ts
- test/slackInteraction.json
> feat: added tests for testing slack interaction

- src/AssumedRoleAlarms.ts
- src/DeploymentEnvironments.ts
- src/MonitoringTargetStage.ts
- src/MpaMonitoringStack.ts
- src/main.ts
- src/monitoringLambda/MessageFormatter.ts
- src/monitoringLambda/test/samples/alarm-from-mpa.json
- src/monitoringLambda/test/sns-handler.test.ts
- src/statics.ts
- FIx for account id when events come from MPA
- Deploy to gn-build account
- Added assume role monitoring in MPA account
> Sandbox new lz

- src/DeploymentEnvironments.ts
> feat: new accounts

- src/SlackInteractivityLambda/SlackInteractivity.lambda.ts
> fix: another bug in the link construction

- src/monitoringLambda/MessageFormatter.ts
> feat: included request parameters in slack message

- src/MonitoringTargetStage.ts
> feat: send requestParameters to slack

- src/DeploymentEnvironments.ts
> feat: monitoring mijn nijmegen accounts

- src/DeploymentEnvironments.ts
> feat: add dummy log query for testing

- src/DeploymentEnvironments.ts
- src/LogQueryJob/QueryFormatter.ts
- Fix to execlude @ptr field in log file
- Test query for us-east-1 (cross region)
- Added relevant queries for beheertaak
> feat: automation of beheertaak (queries and fixes)

- src/DeploymentEnvironments.ts
Add accounts:
- gn-verwerkingenlogging-accp
- gn-verwerkingenlogging-prod
> feat: deploy monitoring to verwerkingenlogging accounts

- src/MpaMonitoringStack.ts
- src/OrgTrailMonitoring.ts
> fix: use environment name instead of bool flag isProd

- src/PipelineStack.ts
> feat: only deploy mpa montiroing lambda from prod branch

- src/DeploymentEnvironments.ts
- src/OrgTrailMonitoring.ts
- src/OrgtrailMonitorLambda/OrgTrailMonitorHandler.ts
- src/OrgtrailMonitorLambda/test/orgTrailSecretEvent.json
- src/OrgtrailMonitorLambda/test/orgtrail.test.ts
- src/SlackInteractivityLambda/SlackInteractivity.lambda.ts
> feat: monitoring secrets and add monitoring rules

- docs/aws-monitoring.md
> chore: move wiki page to docs folder

- src/AggregatorStack.ts
> feat: remove SecurityHub Automation rule

- src/SecurityHubOverviewLambda/SecurityHubOverview.lambda.ts
> fix: message on no findings

- docs/topdesk-api-key.md
Uitleg vervangen topdesk api key
Fixes #145
> chore: create topdesk-api-key.md

- src/DeploymentEnvironments.ts
- src/main.ts
- src/monitoringLambda/MessageFormatter.ts
- src/monitoringLambda/monitoring.lambda.ts
- src/monitoringLambda/test/logs-handler.test.ts
- src/monitoringLambda/test/sns-handler.test.ts
> feat: remove -new-lz suffix from branch names

- src/AggregatorStack.ts
> fix: securityhub notifications were not broken

- src/MonitoredAccountStack.ts
- src/monitoringLambda/SnsEventHandler.ts
> fix: use -lvl suffix for alarms

- src/MonitoredAccountStack.ts
> fix: missing suffix in event filter

- src/DeploymentEnvironments.ts
Since we now have a critical topic, this should be modified.
> feat: EP role is not critical but high

- src/DefaultAlarms.ts
Fixes https://github.com/GemeenteNijmegen/devops/issues/637
> feat: upgrade concurrent-executions to high

- src/DefaultAlarms.ts
> fix: treat missing data as ok

- .projen/deps.json
- .projen/tasks.json
- .projenrc.js
- package.json
- src/EventBusForwardingRule.ts
- src/EventbridgeForwarderStack.ts
- src/MonitoringTargetStage.ts
- yarn.lock
Adds the stack in all monitored accounts to regions eu-west-1 and us-east-1.
> feat: Add eventbridge forwarder stack

- src/DeploymentEnvironments.ts
> feat: changed local deploy to critical priority

- src/DeploymentEnvironments.ts
- src/OrgtrailMonitorLambda/MonitoringEvent.ts
- src/OrgtrailMonitorLambda/OrgTrailMonitorHandler.ts
- src/OrgtrailMonitorLambda/test/orgtrail.test.ts
- src/statics.ts
> feat: account type specific priority

- src/DeploymentEnvironments.ts
> feat: add alarm on oblcc-admin role

- src/DeploymentEnvironments.ts
> feat: do not notify on critical level for sandbox local deploy

- .github/workflows/upgrade-sandbox.yml
- .projenrc.js
> chore: add auto-merge label to upgrade dependencies pr

- src/DeploymentEnvironments.ts
https://github.com/GemeenteNijmegen/devops/issues/887
> chore: delete vierdaagse accoutns from monitoring

- src/DeploymentEnvironments.ts
Fixes #https://github.com/GemeenteNijmegen/devops/issues/895
> chore: remove verwerkingenlogging
